from selenium import webdriver
driver = webdriver.Chrome('C:/Users/AHAD RAZA/Desktop/chromedriver.exe')
driver.get('https://fbise.edu.pk/')
driver.implicitly_wait(10)
driver.find_element_by_xpath('/html/body/header/div[1]/div/div/div/div/div/a[1]/i').click()
driver.implicitly_wait(10)
driver.back()
driver.find_element_by_xpath('/html/body/header/div[1]/div/div/div/div/div/a[2]/i').click()
driver.implicitly_wait(10)
driver.back()
driver.find_element_by_xpath('//*[@id="myModal"]/div/div/div[3]/button').click()
driver.find_element_by_xpath('/html/body/header/div[1]/div/div/div/div/div/a[3]').click()
driver.implicitly_wait(10)
driver.back()
driver.find_element_by_xpath('//*[@id="myModal"]/div/div/div[3]/button').click()
driver.find_element_by_xpath('/html/body/header/div[1]/div/div/div/div/div/a[5]').click()
driver.implicitly_wait(10)
driver.back()
driver.quit()