from selenium import webdriver
driver = webdriver.Chrome('C:/Users/AHAD RAZA/Desktop/chromedriver.exe')
driver.get('https://accounts.google.com/signup/v2/webcreateaccount?hl=en&flowName=GlifWebSignIn&flowEntry=SignUp')
driver.find_element_by_xpath('//*[@id="firstName"]').send_keys('AHAD')
driver.find_element_by_xpath('//*[@id="lastName"]').send_keys('RAZA')
driver.find_element_by_xpath('//*[@id="username"]').send_keys('mrahadrazaofficial')
driver.find_element_by_xpath('//*[@id="passwd"]/div[1]/div/div[1]/input').send_keys('ahadrazaofficial03325514947')
driver.find_element_by_xpath('//*[@id="confirm-passwd"]/div[1]/div/div[1]/input').send_keys('ahadrazaofficial03325514947')
driver.find_element_by_xpath('//*[@id="i3"]').click()
driver.find_element_by_xpath('//*[@id="accountDetailsNext"]/div/button/span').click()
driver.implicitly_wait(10)
driver.find_element_by_xpath('//*[@id="phoneNumberId"]').send_keys('03365645407')
driver.back()
driver.implicitly_wait(10)
driver.quit()